version: 2

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/microservice-movies
    environment:
      - NODE_ENV: test
    parallelism: 1
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: false
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1 \
              bash \
              jq \
              curl
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Build Docker images
          command: docker-compose build
      - run:
          name: Spin up Docker containers
          command: docker-compose up -d
      - run:
          name: Migrate and seed the database
          command: sh init_db.sh
      - run:
          name: Test the user service
          command: docker-compose run users-service npm test
      - run:
          name: Test the movies service
          command: docker-compose run users-service npm test
